### PR TITLE
lib: A sparse file can be created with atomic_create_and_write()

### LINKED ISSUE #227: size of an object grows by multi-disk plug operation
The size of an inode-object is 4KB immediately after create VDI.
after that, the size of the inode-object grow to 12296KB by the recovery of multi disk plug operation.

steps to reproduce:
```
# sheep -c local -p 7001 -z 1 /var/lib/sheepdog/1
# sheep -c local -p 7002 -z 2 /var/lib/sheepdog/2

# dog cluster format -p 7001 -c 2
using backend plain store

# dog vdi create dummy_vdi_01 1M -p 7001
# dog vdi create dummy_vdi_02 1M -p 7001
# dog vdi create dummy_vdi_03 1M -p 7001

# ls -ls /var/lib/sheepdog/1/obj /var/lib/sheepdog/2/obj /var/lib/sheepdog/1/plug_disk1
/var/lib/sheepdog/1/obj:
total 12
4 -rw-r----- 1 root root 12587576 Mar 24 11:26 80817d0800000000
4 -rw-r----- 1 root root 12587576 Mar 24 11:26 80817ebb00000000
4 -rw-r----- 1 root root 12587576 Mar 24 11:26 8081822100000000

/var/lib/sheepdog/1/plug_disk1:
total 0

/var/lib/sheepdog/2/obj:
total 12
4 -rw-r----- 1 root root 12587576 Mar 24 11:26 80817d0800000000
4 -rw-r----- 1 root root 12587576 Mar 24 11:26 80817ebb00000000
4 -rw-r----- 1 root root 12587576 Mar 24 11:26 8081822100000000

# dog node md plug /var/lib/sheepdog/1/plug_disk1 -p 7001
    __
   ()'`;
   /\|`
  /  |   Caution! The directories to be plugged will be purged.
(/_)_|_  Are you sure you want to continue? [yes/no]: yes

# ls -ls /var/lib/sheepdog/1/obj /var/lib/sheepdog/2/obj /var/lib/sheepdog/1/plug_disk1
/var/lib/sheepdog/1/obj:
total 4
4 -rw-r----- 1 root root 12587576 Mar 24 11:26 8081822100000000

/var/lib/sheepdog/1/plug_disk1:
total 24592
12296 -rw-r----- 1 root root 12587576 Mar 24 11:26 80817d0800000000    -----------> here
12296 -rw-r----- 1 root root 12587576 Mar 24 11:26 80817ebb00000000    -----------> here

/var/lib/sheepdog/2/obj:
total 12
4 -rw-r----- 1 root root 12587576 Mar 24 11:26 80817d0800000000
4 -rw-r----- 1 root root 12587576 Mar 24 11:26 80817ebb00000000
4 -rw-r----- 1 root root 12587576 Mar 24 11:26 8081822100000000
```

### PR DESCRIPTION
**Pull request by tmenjo**
This adds a parameter 'sparse' to atomic_create_and_write(). If sparse is true, atomic_create_and_write() should create sparse file. Otherwise, it should do like as before i.e. create non-sparse file.

This also makes md_move_object() in sheep/store/md.c call atomic_create_and_write() with sparse=true. Hereby, object files will be sparsed when they move between disks.

Fixes #227.

Signed-off-by: Takashi Menjo &lt;menjo.takashi@lab.ntt.co.jp&gt;

### CODE REVIEW

File: lib/common.c [hunk 1]
```diff
@@ -65,6 +66,42 @@ int atomic_create_and_write(const char *path, const char *buf, size_t len,
...
+			if (ret < 0) {
+				sd_err("failed to discard file %s, "
+				       "head %" PRIu64 ", %m",
+				       path, nonzero_head);
+				goto close_fd;
+			}
+		}
+
+		const size_t nonzero_tail = nonzero_head + nonzero_len;
+		if(nonzero_tail < len) {
```
Comment (mitake) [inline lib/common.c]: You need a space between if and (

**Comment by mitake** [comment]
@tmenjo the change looks good to me except the very trivial style problem. Could you update for the style problem?

**Comment by tmenjo** [comment]
@mitake Thanks for your review. I updated for the style problem.

**Comment by mitake** [comment]
Merged, thanks.
